
package shipmentcallback;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ShipmentServiceCallbackService", targetNamespace = "http://shipmentcallback/", wsdlLocation = "file:/D:/KTH/Projects/PWS/HWs/Project/BookStore2/src/java/shipmentcallback/wsdl/ShipmentServiceCallbackService.wsdl")
public class ShipmentServiceCallbackService
    extends Service
{

    private final static URL SHIPMENTSERVICECALLBACKSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(shipmentcallback.ShipmentServiceCallbackService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = shipmentcallback.ShipmentServiceCallbackService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/KTH/Projects/PWS/HWs/Project/BookStore2/src/java/shipmentcallback/wsdl/ShipmentServiceCallbackService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/KTH/Projects/PWS/HWs/Project/BookStore2/src/java/shipmentcallback/wsdl/ShipmentServiceCallbackService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SHIPMENTSERVICECALLBACKSERVICE_WSDL_LOCATION = url;
    }

    public ShipmentServiceCallbackService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShipmentServiceCallbackService() {
        super(SHIPMENTSERVICECALLBACKSERVICE_WSDL_LOCATION, new QName("http://shipmentcallback/", "ShipmentServiceCallbackService"));
    }

    /**
     * 
     * @return
     *     returns ShipmentServiceCallback
     */
    @WebEndpoint(name = "ShipmentServiceCallbackPort")
    public ShipmentServiceCallback getShipmentServiceCallbackPort() {
        return super.getPort(new QName("http://shipmentcallback/", "ShipmentServiceCallbackPort"), ShipmentServiceCallback.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShipmentServiceCallback
     */
    @WebEndpoint(name = "ShipmentServiceCallbackPort")
    public ShipmentServiceCallback getShipmentServiceCallbackPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://shipmentcallback/", "ShipmentServiceCallbackPort"), ShipmentServiceCallback.class, features);
    }

}
