
package shipmentcallback;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ShipmentServiceCallback", targetNamespace = "http://shipmentcallback/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShipmentServiceCallback {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "shipmentDone", targetNamespace = "http://shipmentcallback/", className = "shipmentcallback.ShipmentDone")
    @ResponseWrapper(localName = "shipmentDoneResponse", targetNamespace = "http://shipmentcallback/", className = "shipmentcallback.ShipmentDoneResponse")
    public void shipmentDone(
        @WebParam(name = "arg0", targetNamespace = "")
        InvoiceBean arg0);

}
