<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="AuthorizationWSServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/AuthorizationWSServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/AuthorizationWSServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://authorization/">
    <import location="BookStore2/wsdl/AuthorizationWSService.wsdl" namespace="http://authorization/"/>
    <plnk:partnerLinkType name="AuthorizationLinkType">
        <plnk:role name="AuthorizationRequestorRole" portType="ns:AuthorizationWS"/>
        <plnk:role name="AuthorizationProviderRole" portType="ns:AuthorizationWS"/>
    </plnk:partnerLinkType>
</definitions>

