<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PublisherUSAWSServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/PublisherUSAWSServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/PublisherUSAWSServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://bookpublisherUSA/">
    <import location="BookStore2/wsdl/PublisherUSAWSService.wsdl" namespace="http://bookpublisherUSA/"/>
    <plnk:partnerLinkType name="PublisherUSAWSLinkType">
        <plnk:role name="PublisherUSAWSRole" portType="ns:PublisherUSAWS"/>
    </plnk:partnerLinkType>
</definitions>

