
package bookpublisherusacallback;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PublisherUSAWSCallBack", targetNamespace = "http://bookpublisherUSAcallback/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublisherUSAWSCallBack {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "bookOrderDone", targetNamespace = "http://bookpublisherUSAcallback/", className = "bookpublisherusacallback.BookOrderDone")
    @ResponseWrapper(localName = "bookOrderDoneResponse", targetNamespace = "http://bookpublisherUSAcallback/", className = "bookpublisherusacallback.BookOrderDoneResponse")
    public void bookOrderDone(
        @WebParam(name = "arg0", targetNamespace = "")
        SellReturnObj arg0);

}
