
package bookpublishercallback;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PublisherWSCallBackService", targetNamespace = "http://bookpublishercallback/", wsdlLocation = "file:/D:/KTH/Projects/PWS/HWs/Project/BookStore2/src/java/bookpublishercallback/wsdl/PublisherWSCallBackService.wsdl")
public class PublisherWSCallBackService
    extends Service
{

    private final static URL PUBLISHERWSCALLBACKSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(bookpublishercallback.PublisherWSCallBackService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = bookpublishercallback.PublisherWSCallBackService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/KTH/Projects/PWS/HWs/Project/BookStore2/src/java/bookpublishercallback/wsdl/PublisherWSCallBackService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/KTH/Projects/PWS/HWs/Project/BookStore2/src/java/bookpublishercallback/wsdl/PublisherWSCallBackService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PUBLISHERWSCALLBACKSERVICE_WSDL_LOCATION = url;
    }

    public PublisherWSCallBackService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublisherWSCallBackService() {
        super(PUBLISHERWSCALLBACKSERVICE_WSDL_LOCATION, new QName("http://bookpublishercallback/", "PublisherWSCallBackService"));
    }

    /**
     * 
     * @return
     *     returns PublisherWSCallBack
     */
    @WebEndpoint(name = "PublisherWSCallBackPort")
    public PublisherWSCallBack getPublisherWSCallBackPort() {
        return super.getPort(new QName("http://bookpublishercallback/", "PublisherWSCallBackPort"), PublisherWSCallBack.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublisherWSCallBack
     */
    @WebEndpoint(name = "PublisherWSCallBackPort")
    public PublisherWSCallBack getPublisherWSCallBackPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bookpublishercallback/", "PublisherWSCallBackPort"), PublisherWSCallBack.class, features);
    }

}
