//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.06 at 02:45:12 PM CET 
//


package JAXB.CompaniesInfo;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.kth.se/CompaniesInfo}addressExt"/>
 *         &lt;element ref="{http://www.kth.se/CompaniesInfo}numberOfEmployees"/>
 *         &lt;element ref="{http://www.kth.se/CompaniesInfo}foundedYear"/>
 *         &lt;element ref="{http://www.kth.se/CompaniesInfo}CEO"/>
 *         &lt;element ref="{http://www.kth.se/CompaniesInfo}site"/>
 *       &lt;/sequence>
 *       &lt;attribute name="companyName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addressExt",
    "numberOfEmployees",
    "foundedYear",
    "ceo",
    "site"
})
@XmlRootElement(name = "company")
public class Company {

    @XmlElement(required = true)
    protected AddressExt addressExt;
    @XmlElement(required = true)
    protected BigInteger numberOfEmployees;
    protected int foundedYear;
    @XmlElement(name = "CEO", required = true)
    protected String ceo;
    @XmlElement(required = true)
    protected String site;
    @XmlAttribute(name = "companyName")
    protected String companyName;

    /**
     * Gets the value of the addressExt property.
     * 
     * @return
     *     possible object is
     *     {@link AddressExt }
     *     
     */
    public AddressExt getAddressExt() {
        return addressExt;
    }

    /**
     * Sets the value of the addressExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressExt }
     *     
     */
    public void setAddressExt(AddressExt value) {
        this.addressExt = value;
    }

    /**
     * Gets the value of the numberOfEmployees property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfEmployees() {
        return numberOfEmployees;
    }

    /**
     * Sets the value of the numberOfEmployees property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfEmployees(BigInteger value) {
        this.numberOfEmployees = value;
    }

    /**
     * Gets the value of the foundedYear property.
     * 
     */
    public int getFoundedYear() {
        return foundedYear;
    }

    /**
     * Sets the value of the foundedYear property.
     * 
     */
    public void setFoundedYear(int value) {
        this.foundedYear = value;
    }

    /**
     * Gets the value of the ceo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCEO() {
        return ceo;
    }

    /**
     * Sets the value of the ceo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCEO(String value) {
        this.ceo = value;
    }

    /**
     * Gets the value of the site property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSite() {
        return site;
    }

    /**
     * Sets the value of the site property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSite(String value) {
        this.site = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

}
