//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.06 at 04:01:39 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kth.se/Transcript", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package JAXB.Transcript;
