<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PublisherWSCallBackServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/PublisherWSCallBackServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/PublisherWSCallBackServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://bookpublishercallback/">
    <import location="PublisherWSCallBackService.wsdl" namespace="http://bookpublishercallback/"/>
    <plnk:partnerLinkType name="PublisherWSCallBackLinkType">
        <plnk:role name="PublisherWSCallBackRole" portType="ns:PublisherWSCallBack"/>
    </plnk:partnerLinkType>
</definitions>

