
package bookpublishercallback;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PublisherWSCallBack", targetNamespace = "http://bookpublishercallback/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublisherWSCallBack {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "bookOrderDone", targetNamespace = "http://bookpublishercallback/", className = "bookpublishercallback.BookOrderDone")
    public void bookOrderDone(
        @WebParam(name = "arg0", targetNamespace = "")
        SellReturnObj arg0);

}
